rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

notifications:
  email:
    - robert.e.hallgren@hp.com
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=4.3.2

matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_VERSION=3.3.1
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.3.2
