rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

notifications:
  email:
    - robert.e.hallgren@hp.com
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.6.0"
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 4.3.2"

matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.3.2"

